if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()
file(GLOB_RECURSE VIEWER_PUBLIC_HEADERS "${SOURCE_ROOT}/src/viewer/include/*.hpp")
if(NOT VIEWER_PUBLIC_HEADERS)
  message(FATAL_ERROR "No provider-neutral Viewer public headers found")
endif()
set(FORBIDDEN_VIEWER_TOKENS "TopoDS_" "AIS_" "V3d_" "Graphic3d_" "OpenCASCADE" "#include <Q" "#include <Qt")
foreach(HEADER IN LISTS VIEWER_PUBLIC_HEADERS)
  file(READ "${HEADER}" CONTENT)
  foreach(TOKEN IN LISTS FORBIDDEN_VIEWER_TOKENS)
    string(FIND "${CONTENT}" "${TOKEN}" POSITION)
    if(NOT POSITION EQUAL -1)
      message(FATAL_ERROR "Provider-neutral Viewer header leaks forbidden token '${TOKEN}': ${HEADER}")
    endif()
  endforeach()
endforeach()
file(GLOB_RECURSE DOMAIN_SOURCES "${SOURCE_ROOT}/src/core/*" "${SOURCE_ROOT}/src/part/*" "${SOURCE_ROOT}/src/application/*")
foreach(FILE_PATH IN LISTS DOMAIN_SOURCES)
  if(IS_DIRECTORY "${FILE_PATH}")
    continue()
  endif()
  file(READ "${FILE_PATH}" CONTENT)
  foreach(TOKEN IN ITEMS "viewer_qt_occt" "TopoDS_" "AIS_" "V3d_" "Graphic3d_")
    string(FIND "${CONTENT}" "${TOKEN}" POSITION)
    if(NOT POSITION EQUAL -1)
      message(FATAL_ERROR "Domain/application source leaks Viewer provider token '${TOKEN}': ${FILE_PATH}")
    endif()
  endforeach()
endforeach()
